nodeLinker: node-modules

npmScopes:
  awesome.me:
    npmAlwaysAuth: true
    npmAuthToken: 3CCC982D-6683-49A8-A178-86730A4687C5
    npmRegistryServer: "https://npm.fontawesome.com/"
  fortawesome:
    npmAlwaysAuth: true
    npmAuthToken: 3CCC982D-6683-49A8-A178-86730A4687C5
    npmRegistryServer: "https://npm.fontawesome.com/"
